use serde::{Deserialize, Deserializer};

// Language codes taken from <https://www.rssboard.org/rss-language-codes> and
// <https://www.loc.gov/standards/iso639-2/php/code_list.php>.
#[derive(Debug, PartialEq)]
pub enum Language {
    Afar,
    Abkhazian,
    Avestan,
    Afrikaans,
    Akan,
    Amharic,
    Aragonese,
    Arabic,
    Assamese,
    Avaric,
    Aymara,
    Azerbaijani,
    Bashkir,
    Belarusian,
    Bulgarian,
    BihariLanguages,
    Bislama,
    Bambara,
    Bengali,
    Tibetan,
    Breton,
    Bosnian,
    Catalan,
    Chechen,
    Chamorro,
    Corsican,
    Cree,
    Czech,
    SlavicChurch,
    Chuvash,
    Welsh,
    Danish,
    German,
    GermanAustria,
    GermanSwitzerland,
    GermanGermany,
    GermanLiechtenstein,
    GermanLuxembourg,
    Divehi,
    Ewe,
    Greek,
    English,
    EnglishAustralia,
    EnglishBelize,
    EnglishCanada,
    EnglishUnitedKingdom,
    EnglishIreland,
    EnglishJamaica,
    EnglishNewZealand,
    EnglishPhillipines,
    EnglishTrinidad,
    EnglishUnitedStates,
    EnglishSouthAfrica,
    EnglishZimbabwe,
    Esperanto,
    Spanish,
    SpanishArgentina,
    SpanishBolivia,
    SpanishChile,
    SpanishColombia,
    SpanishCostaRica,
    SpanishDominicanRepublic,
    SpanishEcuador,
    SpanishSpain,
    SpanishGuatemala,
    SpanishHonduras,
    SpanishMexico,
    SpanishNicaragua,
    SpanishPanama,
    SpanishPeru,
    SpanishPuertoRico,
    SpanishParaguay,
    SpanishElSalvador,
    SpanishUruguay,
    SpanishVenezuela,
    Estonian,
    Basque,
    Persian,
    Fulah,
    Finnish,
    Fijian,
    Faeroese,
    Faroese,
    French,
    FrenchBelgium,
    FrenchCanada,
    FrenchSwitzerland,
    FrenchFrance,
    FrenchLuxembourg,
    FrenchMonaco,
    WesternFrisian,
    Irish,
    Gaelic,
    Galician,
    Guarani,
    Gujarati,
    Manx,
    Hausa,
    Hawaiian,
    Hebrew,
    Hindi,
    HiriMotu,
    Croatian,
    Haitian,
    Hungarian,
    Armenian,
    Herero,
    Interlingua,
    Interlingue,
    Igbo,
    SichuanYi,
    Inupiaq,
    Indonesian,
    Ido,
    Icelandic,
    Italian,
    ItalianSwitzerland,
    ItalianItaly,
    Inuktitut,
    Japanese,
    Javanese,
    Georgian,
    Kongo,
    KikuyuGikuyu,
    Kuanyama,
    Kazakh,
    Kalaallisut,
    CentralKhmer,
    Kannada,
    Korean,
    Kanuri,
    Kashmiri,
    Kurdish,
    Komi,
    Cornish,
    KirghizKyrgyz,
    Latin,
    Luxembourgish,
    Ganda,
    Limburgan,
    Lingala,
    Lao,
    Lithuanian,
    LubaKatanga,
    Latvian,
    Malagasy,
    Marshallese,
    Maori,
    Macedonian,
    Malayalam,
    Mongolian,
    Marathi,
    Malay,
    Maltese,
    Burmese,
    Nauru,
    NorwegianBokmal,
    Nepali,
    Ndonga,
    Dutch,
    Dzongkha,
    DutchBelgium,
    DutchNetherlands,
    NorwegianNynorsk,
    Norwegian,
    Ndebele,
    Navajo,
    Chichewa,
    Occitan,
    Ojibwa,
    Oromo,
    Oriya,
    Ossetian,
    Panjabi,
    Pali,
    Polish,
    Pushto,
    Portuguese,
    PortugueseBrazil,
    PortuguesePortugal,
    Quechua,
    Romansh,
    Rundi,
    Romanian,
    RomanianMoldova,
    RomanianRomania,
    Russian,
    RussianMoldova,
    RussianRussia,
    Kinyarwanda,
    Sanskrit,
    Sardinian,
    Sindhi,
    NorthernSami,
    Sango,
    Sinhala,
    Slovak,
    Slovenian,
    Samoan,
    Shona,
    Somali,
    Albanian,
    Serbian,
    Swati,
    SothoSouthern,
    Sundanese,
    Swedish,
    SwedishFinland,
    SwedishSweden,
    Swahili,
    Tamil,
    Telugu,
    Tajik,
    Thai,
    Tigrinya,
    Turkmen,
    Tagalog,
    Tswana,
    Tonga,
    Turkish,
    Tsonga,
    Tatar,
    Twi,
    Tahitian,
    Uighur,
    Ukrainian,
    Ukranian,
    Urdu,
    Uzbek,
    Venda,
    Vietnamese,
    Volapük,
    Walloon,
    Wolof,
    Xhosa,
    Yiddish,
    Yoruba,
    Zhuang,
    Chinese,
    ChineseSimplified,
    ChineseTraditional,
    Zulu,

    Other(String),
}

impl<'de> Deserialize<'de> for Language {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = match String::deserialize(d) {
            Ok(s) => s,
            Err(e) => return Err(e),
        };

        match s.as_str() {
            "aa" => Ok(Language::Afar),
            "ab" => Ok(Language::Abkhazian),
            "ae" => Ok(Language::Avestan),
            "af" => Ok(Language::Afrikaans),
            "ak" => Ok(Language::Akan),
            "am" => Ok(Language::Amharic),
            "an" => Ok(Language::Aragonese),
            "ar" => Ok(Language::Arabic),
            "as" => Ok(Language::Assamese),
            "av" => Ok(Language::Avaric),
            "ay" => Ok(Language::Aymara),
            "az" => Ok(Language::Azerbaijani),
            "ba" => Ok(Language::Bashkir),
            "be" => Ok(Language::Belarusian),
            "bg" => Ok(Language::Bulgarian),
            "bh" => Ok(Language::BihariLanguages),
            "bi" => Ok(Language::Bislama),
            "bm" => Ok(Language::Bambara),
            "bn" => Ok(Language::Bengali),
            "bo" => Ok(Language::Tibetan),
            "br" => Ok(Language::Breton),
            "bs" => Ok(Language::Bosnian),
            "ca" => Ok(Language::Catalan),
            "ce" => Ok(Language::Chechen),
            "ch" => Ok(Language::Chamorro),
            "co" => Ok(Language::Corsican),
            "cr" => Ok(Language::Cree),
            "cs" => Ok(Language::Czech),
            "cu" => Ok(Language::SlavicChurch),
            "cv" => Ok(Language::Chuvash),
            "cy" => Ok(Language::Welsh),
            "da" => Ok(Language::Danish),
            "de" => Ok(Language::German),
            "de-at" => Ok(Language::GermanAustria),
            "de-ch" => Ok(Language::GermanSwitzerland),
            "de-de" => Ok(Language::GermanGermany),
            "de-li" => Ok(Language::GermanLiechtenstein),
            "de-lu" => Ok(Language::GermanLuxembourg),
            "dv" => Ok(Language::Divehi),
            "dz" => Ok(Language::Dzongkha),
            "ee" => Ok(Language::Ewe),
            "el" => Ok(Language::Greek),
            "en" => Ok(Language::English),
            "en-au" => Ok(Language::EnglishAustralia),
            "en-bz" => Ok(Language::EnglishBelize),
            "en-ca" => Ok(Language::EnglishCanada),
            "en-gb" => Ok(Language::EnglishUnitedKingdom),
            "en-ie" => Ok(Language::EnglishIreland),
            "en-jm" => Ok(Language::EnglishJamaica),
            "en-nz" => Ok(Language::EnglishNewZealand),
            "en-ph" => Ok(Language::EnglishPhillipines),
            "en-tt" => Ok(Language::EnglishTrinidad),
            "en-us" => Ok(Language::EnglishUnitedStates),
            "en-za" => Ok(Language::EnglishSouthAfrica),
            "en-zw" => Ok(Language::EnglishZimbabwe),
            "eo" => Ok(Language::Esperanto),
            "es" => Ok(Language::Spanish),
            "es-ar" => Ok(Language::SpanishArgentina),
            "es-bo" => Ok(Language::SpanishBolivia),
            "es-cl" => Ok(Language::SpanishChile),
            "es-co" => Ok(Language::SpanishColombia),
            "es-cr" => Ok(Language::SpanishCostaRica),
            "es-do" => Ok(Language::SpanishDominicanRepublic),
            "es-ec" => Ok(Language::SpanishEcuador),
            "es-es" => Ok(Language::SpanishSpain),
            "es-gt" => Ok(Language::SpanishGuatemala),
            "es-hn" => Ok(Language::SpanishHonduras),
            "es-mx" => Ok(Language::SpanishMexico),
            "es-ni" => Ok(Language::SpanishNicaragua),
            "es-pa" => Ok(Language::SpanishPanama),
            "es-pe" => Ok(Language::SpanishPeru),
            "es-pr" => Ok(Language::SpanishPuertoRico),
            "es-py" => Ok(Language::SpanishParaguay),
            "es-sv" => Ok(Language::SpanishElSalvador),
            "es-uy" => Ok(Language::SpanishUruguay),
            "es-ve" => Ok(Language::SpanishVenezuela),
            "et" => Ok(Language::Estonian),
            "eu" => Ok(Language::Basque),
            "fa" => Ok(Language::Persian),
            "ff" => Ok(Language::Fulah),
            "fi" => Ok(Language::Finnish),
            "fj" => Ok(Language::Fijian),
            "fo" => Ok(Language::Faroese),
            "fr" => Ok(Language::French),
            "fr-be" => Ok(Language::FrenchBelgium),
            "fr-ca" => Ok(Language::FrenchCanada),
            "fr-ch" => Ok(Language::FrenchSwitzerland),
            "fr-fr" => Ok(Language::FrenchFrance),
            "fr-lu" => Ok(Language::FrenchLuxembourg),
            "fr-mc" => Ok(Language::FrenchMonaco),
            "fy" => Ok(Language::WesternFrisian),
            "ga" => Ok(Language::Irish),
            "gd" => Ok(Language::Gaelic),
            "gl" => Ok(Language::Galician),
            "gn" => Ok(Language::Guarani),
            "gu" => Ok(Language::Gujarati),
            "gv" => Ok(Language::Manx),
            "ha" => Ok(Language::Hausa),
            "haw" => Ok(Language::Hawaiian),
            "he" => Ok(Language::Hebrew),
            "hi" => Ok(Language::Hindi),
            "ho" => Ok(Language::HiriMotu),
            "hr" => Ok(Language::Croatian),
            "ht" => Ok(Language::Haitian),
            "hu" => Ok(Language::Hungarian),
            "hy" => Ok(Language::Armenian),
            "hz" => Ok(Language::Herero),
            "ia" => Ok(Language::Interlingua),
            "ie" => Ok(Language::Interlingue),
            "ig" => Ok(Language::Igbo),
            "ii" => Ok(Language::SichuanYi),
            "ik" => Ok(Language::Inupiaq),
            "in" => Ok(Language::Indonesian),
            "io" => Ok(Language::Ido),
            "is" => Ok(Language::Icelandic),
            "it" => Ok(Language::Italian),
            "it-ch" => Ok(Language::ItalianSwitzerland),
            "it-it" => Ok(Language::ItalianItaly),
            "iu" => Ok(Language::Inuktitut),
            "ja" => Ok(Language::Japanese),
            "jv" => Ok(Language::Javanese),
            "ka" => Ok(Language::Georgian),
            "kg" => Ok(Language::Kongo),
            "ki" => Ok(Language::KikuyuGikuyu),
            "kj" => Ok(Language::Kuanyama),
            "kk" => Ok(Language::Kazakh),
            "kl" => Ok(Language::Kalaallisut),
            "km" => Ok(Language::CentralKhmer),
            "kn" => Ok(Language::Kannada),
            "ko" => Ok(Language::Korean),
            "kr" => Ok(Language::Kanuri),
            "ks" => Ok(Language::Kashmiri),
            "ku" => Ok(Language::Kurdish),
            "kv" => Ok(Language::Komi),
            "kw" => Ok(Language::Cornish),
            "ky" => Ok(Language::KirghizKyrgyz),
            "la" => Ok(Language::Latin),
            "lb" => Ok(Language::Luxembourgish),
            "lg" => Ok(Language::Ganda),
            "li" => Ok(Language::Limburgan),
            "ln" => Ok(Language::Lingala),
            "lo" => Ok(Language::Lao),
            "lt" => Ok(Language::Lithuanian),
            "lu" => Ok(Language::LubaKatanga),
            "lv" => Ok(Language::Latvian),
            "mg" => Ok(Language::Malagasy),
            "mh" => Ok(Language::Marshallese),
            "mi" => Ok(Language::Maori),
            "mk" => Ok(Language::Macedonian),
            "ml" => Ok(Language::Malayalam),
            "mn" => Ok(Language::Mongolian),
            "mr" => Ok(Language::Marathi),
            "ms" => Ok(Language::Malay),
            "mt" => Ok(Language::Maltese),
            "my" => Ok(Language::Burmese),
            "na" => Ok(Language::Nauru),
            "nb" => Ok(Language::NorwegianBokmal),
            "ne" => Ok(Language::Nepali),
            "ng" => Ok(Language::Ndonga),
            "nl" => Ok(Language::Dutch),
            "nl-be" => Ok(Language::DutchBelgium),
            "nl-nl" => Ok(Language::DutchNetherlands),
            "nn" => Ok(Language::NorwegianNynorsk),
            "no" => Ok(Language::Norwegian),
            "nr" => Ok(Language::Ndebele),
            "nv" => Ok(Language::Navajo),
            "ny" => Ok(Language::Chichewa),
            "oc" => Ok(Language::Occitan),
            "oj" => Ok(Language::Ojibwa),
            "om" => Ok(Language::Oromo),
            "or" => Ok(Language::Oriya),
            "os" => Ok(Language::Ossetian),
            "pa" => Ok(Language::Panjabi),
            "pi" => Ok(Language::Pali),
            "pl" => Ok(Language::Polish),
            "ps" => Ok(Language::Pushto),
            "pt" => Ok(Language::Portuguese),
            "pt-br" => Ok(Language::PortugueseBrazil),
            "pt-pt" => Ok(Language::PortuguesePortugal),
            "qu" => Ok(Language::Quechua),
            "rm" => Ok(Language::Romansh),
            "rn" => Ok(Language::Rundi),
            "ro" => Ok(Language::Romanian),
            "ro-mo" => Ok(Language::RomanianMoldova),
            "ro-ro" => Ok(Language::RomanianRomania),
            "ru" => Ok(Language::Russian),
            "ru-mo" => Ok(Language::RussianMoldova),
            "ru-ru" => Ok(Language::RussianRussia),
            "rw" => Ok(Language::Kinyarwanda),
            "sa" => Ok(Language::Sanskrit),
            "sc" => Ok(Language::Sardinian),
            "sd" => Ok(Language::Sindhi),
            "se" => Ok(Language::NorthernSami),
            "sg" => Ok(Language::Sango),
            "si" => Ok(Language::Sinhala),
            "sk" => Ok(Language::Slovak),
            "sl" => Ok(Language::Slovenian),
            "sm" => Ok(Language::Samoan),
            "sn" => Ok(Language::Shona),
            "so" => Ok(Language::Somali),
            "sq" => Ok(Language::Albanian),
            "sr" => Ok(Language::Serbian),
            "ss" => Ok(Language::Swati),
            "st" => Ok(Language::SothoSouthern),
            "su" => Ok(Language::Sundanese),
            "sv" => Ok(Language::Swedish),
            "sv-fi" => Ok(Language::SwedishFinland),
            "sv-se" => Ok(Language::SwedishSweden),
            "sw" => Ok(Language::Swahili),
            "ta" => Ok(Language::Tamil),
            "te" => Ok(Language::Telugu),
            "tg" => Ok(Language::Tajik),
            "th" => Ok(Language::Thai),
            "ti" => Ok(Language::Tigrinya),
            "tk" => Ok(Language::Turkmen),
            "tl" => Ok(Language::Tagalog),
            "tn" => Ok(Language::Tswana),
            "to" => Ok(Language::Tonga),
            "tr" => Ok(Language::Turkish),
            "ts" => Ok(Language::Tsonga),
            "tt" => Ok(Language::Tatar),
            "tw" => Ok(Language::Twi),
            "ty" => Ok(Language::Tahitian),
            "ug" => Ok(Language::Uighur),
            "uk" => Ok(Language::Ukrainian),
            "ur" => Ok(Language::Urdu),
            "uz" => Ok(Language::Uzbek),
            "ve" => Ok(Language::Venda),
            "vi" => Ok(Language::Vietnamese),
            "vo" => Ok(Language::Volapük),
            "wa" => Ok(Language::Walloon),
            "wo" => Ok(Language::Wolof),
            "xh" => Ok(Language::Xhosa),
            "yi" => Ok(Language::Yiddish),
            "yo" => Ok(Language::Yoruba),
            "za" => Ok(Language::Zhuang),
            "zh" => Ok(Language::Chinese),
            "zh-cn" => Ok(Language::ChineseSimplified),
            "zh-tw" => Ok(Language::ChineseTraditional),
            "zu" => Ok(Language::Zulu),
            _ => Ok(Language::Other(s)),
        }
    }
}
